### ISSUE TITLE
使用外部Props

### ISSUE THREAD

**Issue by cjloveqhy** [elonehoo/unplugin-vue-prop#5]
1. 在使用`defineProps<xxxProps>()`时，需要导入完整路径

    如下例，该种情况无法正常导入并使用，需明确指定路径，以`index`命名也不可省略
   `import { xxxProps } from '../type'`

    正确的例子如下：
   `import { xxxProps } from '../type/index'`
   或
   `import { xxxProps } from '../type/props'` 等等
2. ts文件编写
    错误示例：
    ```ts
    interface HelloWord {
      msg: string | null
    }

   export { HelloWord }
    ```
    正确示例：
    ```ts
    export interface HelloWord {
      msg: string | null
    }

    ```

**Comment by elonehoo** [comment]
不好意思，我确实无法立刻实现这种效果，不过我在 [v0.0.4](https://github.com/elonehoo/unplugin-vue-prop/tree/v0.0.4)中新增了全局类型这个特性，我想这个新特性可以使用曲线救国的方式完成你的想法。

**Comment by elonehoo** [comment]
具体可以[查看](https://github.com/elonehoo/unplugin-vue-prop/tree/main/playground)
